# Generated by Django 2.1.7 on 2019-08-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
