# Generated by Django 3.0.2 on 2020-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_auto_20200124_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('a', 'Approved'), ('w', 'Waiting'), ('d', 'Denied')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('a', 'Approved'), ('w', 'Waiting'), ('d', 'Denied')], default='w', max_length=1),
        ),
    ]
