# Generated by Django 3.0.2 on 2020-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0011_auto_20200127_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='goal',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
